title: 蝦米碗糕之家
email: motorgp2004@icloud.com
description: >-
  紀錄生活大小事。
baseurl: ""
url: "https://motorgp2004-prog.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
locale: zh_TW
show_excerpts: true
permalink: /:year/:month/:day/:title/
header_pages:
  - index.md
  - about.md
  - portfolio.md
  - downloads.md
minima:
  skin: auto
  social_links:
    github: motorgp2004-prog
