title: 我的部落格
email: you@example.com
description: >-
  分享生活、學習與作品，手機也能更新的免費部落格。
baseurl: ""
url: "https://motorgp2004-prog.github.io"
theme: minima
plugins:
  - jekyll-feed
locale: zh_TW
show_excerpts: true
header_pages:
  - about.md
  - portfolio.md
minima:
  skin: auto
  social_links:
    github: motorgp2004-prog
